version: '3.8'
services:
 backend_bff:
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: api_intermedia
    restart: unless-stopped
    ports:
      - "4000:4000" 
    environment:
      PORT: ${PORT}
      API_URL: ${API_URL}  
    env_file:
      - .env 